apiVersion: 1
datasources:
  - name: LureGuard-PostgreSQL
    type: postgres
    url: postgres:5432
    database: lureguard
    user: lureguard
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
