apiVersion: 1

datasources:
  - name: LureGuard-PostgreSQL
    uid: lureguard-pg
    type: postgres
    access: proxy
    url: postgres:5432
    database: lureguard
    user: lureguard
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: false
