"""create_tables

Revision ID: 5e1281735254
Revises: 10dd818d27d1
Create Date: 2026-06-04 15:59:32.244908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e1281735254'
down_revision: Union[str, None] = '10dd818d27d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('src_ip', postgresql.INET(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('wazuh_rule_id', sa.Integer(), nullable=True),
    sa.Column('wazuh_rule_level', sa.Integer(), nullable=True),
    sa.Column('ingestion_path', sa.String(length=16), nullable=True),
    sa.Column('syscheck_path', sa.Text(), nullable=True),
    sa.Column('syscheck_event', sa.String(length=16), nullable=True),
    sa.Column('syscheck_sha256_after', sa.String(length=64), nullable=True),
    sa.Column('raw_ref', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_src_ip_ts', 'events', ['src_ip', 'ts'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('src_ip', postgresql.INET(), nullable=True),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whitelist',
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('p', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('t1', sa.Float(), nullable=True),
    sa.Column('t2', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('features_hash', sa.String(length=64), nullable=True),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_ts', 'decisions', ['ts'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('summaries')
    op.drop_index('ix_decisions_ts', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('whitelist')
    op.drop_table('sessions')
    op.drop_index('ix_events_src_ip_ts', table_name='events')
    op.drop_table('events')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
