"""Sync Postgres access for MCP tools — thin re-export layer."""

from __future__ import annotations

from lureguard_mcp.repos.connection import get_conn

from lureguard_mcp.repos.actions import (
    log_agent_action,
)
from lureguard_mcp.repos.events import (
    _agent_event_filter,
    _event_enriched_select,
    count_agent_alerts_24h_db,
    get_agent_channels_active_24h_db,
    get_agent_events_last_at_db,
    get_agent_rules_firing_24h_db,
    get_alerts_for_ip,
    get_attack_summary,
    get_event_timeline,
    get_high_level_events_since_db,
    get_recent_alerts,
    is_event_watched_db,
    mark_event_watched_db,
    search_events,
)
from lureguard_mcp.repos.investigations import (
    _next_evidence_id,
    add_timeline_event,
    close_investigation_db,
    get_investigation_findings_db,
    get_investigation_iocs_db,
    get_investigation_timeline_db,
    open_investigation,
    record_finding,
    save_report_db,
)
from lureguard_mcp.repos.posture import (
    create_posture_scan_job_db,
    get_agent_cve_counts_db,
    get_agent_cve_findings_db,
    get_agent_cve_last_scan_db,
    get_agent_detection_coverage_db,
    get_agent_exposure_counts_db,
    get_agent_exposure_findings_db,
    get_agent_exposure_last_scan_db,
    get_agent_sca_last_scan_db,
    get_agent_sca_summary_db,
    get_agent_user_findings_db,
    get_agent_user_last_scan_db,
    get_agent_user_risk_counts_db,
    get_container_cve_findings_db,
    get_container_cve_last_scan_db,
    get_container_cve_counts_db,
    get_container_runtime_db,
    get_fleet_cve_summary_db,
    get_fleet_detection_coverage_db,
    get_fleet_exposure_summary_db,
    get_fleet_sca_summary_db,
    get_host_eol_os_db,
    get_posture_scan_job_db,
    get_soc_health_db,
    replace_agent_cve_findings_db,
    replace_agent_exposure_findings_db,
    replace_agent_sca_findings_db,
    replace_agent_user_findings_db,
    replace_container_cve_findings_db,
    upsert_container_runtime_db,
    set_host_eol_os_db,
    update_posture_scan_job_db,
    upsert_detection_coverage_db,
)
from lureguard_mcp.repos.hosts import (
    get_host_criticality_db,
    get_host_ip_db,
    list_hosts_db,
    set_host_criticality_db,
    upsert_host_db,
)
from lureguard_mcp.repos.blocklist import (
    add_blocklist_db,
    confirm_blocklist_db,
    get_blocklist_entry_db,
    list_blocklist_db,
)
from lureguard_mcp.repos.whitelist import (
    add_whitelist_db,
    confirm_whitelist_db,
    get_whitelist_entry_db,
    list_whitelist_db,
    remove_whitelist_db,
)

# Re-export _agent_event_filter from events for tests/internal use
from lureguard_mcp.repos.events import _agent_event_filter  # noqa: E402

__all__ = [
"_agent_event_filter",
    "_event_enriched_select",
    "_next_evidence_id",
    "add_blocklist_db",
    "add_whitelist_db",
    "add_timeline_event",
    "close_investigation_db",
    "confirm_blocklist_db",
    "confirm_whitelist_db",
    "count_agent_alerts_24h_db",
    "create_posture_scan_job_db",
    "get_agent_channels_active_24h_db",
    "get_agent_cve_counts_db",
    "get_agent_cve_findings_db",
    "get_agent_cve_last_scan_db",
    "get_agent_detection_coverage_db",
    "get_agent_events_last_at_db",
    "get_agent_exposure_counts_db",
    "get_agent_exposure_findings_db",
    "get_agent_exposure_last_scan_db",
    "get_agent_rules_firing_24h_db",
    "get_agent_sca_last_scan_db",
    "get_agent_sca_summary_db",
    "get_agent_user_findings_db",
    "get_agent_user_last_scan_db",
    "get_agent_user_risk_counts_db",
    "get_alerts_for_ip",
    "get_attack_summary",
    "get_blocklist_entry_db",
    "get_whitelist_entry_db",
    "get_conn",
    "get_container_cve_findings_db",
    "get_container_cve_last_scan_db",
    "get_container_cve_counts_db",
    "get_container_runtime_db",
    "get_event_timeline",
    "get_fleet_cve_summary_db",
    "get_fleet_detection_coverage_db",
    "get_fleet_exposure_summary_db",
    "get_fleet_sca_summary_db",
    "get_high_level_events_since_db",
    "get_host_criticality_db",
    "get_host_eol_os_db",
    "get_host_ip_db",
    "get_investigation_findings_db",
    "get_investigation_iocs_db",
    "get_investigation_timeline_db",
    "get_posture_scan_job_db",
    "get_recent_alerts",
    "get_soc_health_db",
    "is_event_watched_db",
    "list_blocklist_db",
    "list_whitelist_db",
    "list_hosts_db",
    "log_agent_action",
    "mark_event_watched_db",
    "open_investigation",
    "remove_whitelist_db",
    "record_finding",
    "replace_agent_cve_findings_db",
    "replace_agent_exposure_findings_db",
    "replace_agent_sca_findings_db",
    "replace_agent_user_findings_db",
    "replace_container_cve_findings_db",
    "upsert_container_runtime_db",
    "save_report_db",
    "search_events",
    "set_host_criticality_db",
    "set_host_eol_os_db",
    "update_posture_scan_job_db",
    "upsert_detection_coverage_db",
    "upsert_host_db",
]
